version: '3.8'

services:
  mongo: 
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  user-service: 
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  
  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq_node
    ports:
      - "5672:5672"
      - "15672:15672"

  task-service: 
    build: ./task-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - rabbitmq

  notification-service: 
    build: ./notification-service
    container_name: notification-service
    ports: 
      - "3003:3003"
    depends_on: 
      - mongo
      - rabbitmq

volumes:
  mongo_data: